In [2]:
#concatinate ,split
import numpy as np
arr1=np.array([20,30,40])
arr2=np.array([50,60,70])
print(np.concatenate([arr1,arr2]))

[20 30 40 50 60 70]


In [13]:
print(np.concatenate([arr1,arr2]))

[20 30 40 50 60 70]


In [4]:
print(np.array_split(arr1,2))

[array([20, 30]), array([40])]


In [17]:
#append, insert ,delete
print(np.append(arr1,[59,49]))

[20 30 40 59 49]


In [18]:
print(np.insert(arr1,1,[22,33]))

[20 22 33 30 40]


In [5]:
arr3=np.array([[10,20,30],[50,60,70]])
arr4=np.array([[10,20,30],[50,60,70]])
print(np.insert(arr3,1,[22,55,77],axis=0))

[[10 20 30]
 [22 55 77]
 [50 60 70]]


In [60]:
print(np.insert(arr3,1,[22,55],axis=1))

[[10 22 20 30]
 [50 55 60 70]]


In [13]:
print(np.delete(arr3,0,axis=1))
#print(np.delete(arr4,[1,2]))

[[20 30]
 [60 70]]


In [14]:
#sort,filter,search
arr5=np.array([2,4,6,3,7,3,7,9])
print(np.short(arr5))

[2 4 6 3 7 3 7 9]


In [6]:
arr6 = np.array([2,5,7,9,5,3,7,4])
print( np.where(arr6% 2 == 0))

(array([0, 7]),)


In [19]:
print(arr6[arr6>4])

[5 7 9 5 7]


In [3]:
#aggregate function
arr7 = np.array([20,30,40,60,70,80])
print(np.sum(arr7))
print(np.min(arr7))
print(np.max(arr7))
print(np.size(arr7))
print(np.mean(arr7))
print(np.cumsum(arr7))
print(np.cumprod(arr7))

300
20
80
6
50.0
[ 20  50  90 150 220 300]
[        20        600      24000    1440000  100800000 8064000000]


In [11]:
a=[100,140,400,600,700,800,400,300]
b=[10,50,30,50,50,30,10,90]
price = np.array(a)
quantity = np.array(b)
print(price,"\n",quantity,"\n","\n")


[100 140 400 600 700 800 400 300] 
 [10 50 30 50 50 30 10 90] 
 

[[  100   140   400   600   700   800   400   300]
 [ 1000  7000 12000 30000 35000 24000  4000 27000]]


In [19]:
c=np.cumprod([price,quantity],axis=0)
print(c)
#print(c[0])
print(c[1])
print(c[1].sum())

[[  100   140   400   600   700   800   400   300]
 [ 1000  7000 12000 30000 35000 24000  4000 27000]]
[ 1000  7000 12000 30000 35000 24000  4000 27000]
140000


In [26]:
#statical function
import statistics as stat
bakedFood=[10,20,40,60,30,40,30,30,80,70,70]
a=np.array(bakedFood)

print(np.mean(bakedFood))
print(np.median(bakedFood))
print(stat.mode(bakedFood)) #numpy have no "mode" attribute
print(np.std(bakedFood)) #stenderd deviation

43.63636363636363
40.0
30
21.85602778212965


In [29]:
tobacco_consumption = [30,50,10,30,50,40]
deaths = [100,120,70,100,120,112]
print(np.corrcoef([tobacco_consumption,deaths])) #positive valu means proportional, negative means inversly proportional


[[1.         0.99015454]
 [0.99015454 1.        ]]
